http base auth added
the-c0d3r/admin-finder pull request #10
Opened 2019-04-21 18:40 UTC by rusmonkey

2019-04-24 04:08 UTC, the-c0d3r commented
Hi @rusmonkey thanks for the PR. 
May I know what's the use case for the http basic authentication? This tool is supposed to work on targets where you normally do not have access to any credentials. Similar to the dirbuster in Kali linux, it is intended to be a penetration testing tool to help you bruteforce the URLs. 

If you can provide a solid use case, I will consider merging it, after a few modifications.

2019-04-24 12:39 UTC, rusmonkey commented
For example, http://tasks.realctf.pro:37243/, ctf task, where you should bruteforce credentials for basic Auth and ater that you need to find admin panel and bruteforce creds for it

2019-04-25 12:14 UTC, the-c0d3r requested changes
That use case you mentioned seem to be only suitable for the specific CTF scenairos. But I intend to modify this tool to be a bit more general purpose URL bruteforcing tool in the future. Thanks for your PR. 

Please make some necessary changes as follows. 
And please remove the unnecessary files as well (eg. `.idea/*`, `__pycache__/*`, `*.pyc` files)

2019-04-25 12:14 UTC, the-c0d3r commented on admin-finder.py
> +    parser.add_argument("-w", "--wordlist", help="Wordlist to use, default 'wordlist.txt'")
👍 for catching the lowercase typo.

2019-04-25 12:14 UTC, the-c0d3r commented on lib/connection.py
> +                connect to the url and return the response
Please align it to the indentation of `"""`

2019-04-25 12:14 UTC, the-c0d3r commented on admin-finder.py
> +    parser.add_argument("-b", "--baseauth", nargs='+',  help="Basic http auth conditionals")
```suggestion
    parser.add_argument("-c", "--credentials", help="Basic http authentication credentials user:pass format")
```

2019-04-25 12:14 UTC, the-c0d3r commented on lib/connection.py
> +    def connect(self, url: str, creds) -> dict:
```suggestion
    def connect(self, url: str, creds: [str, str]) -> dict:
```

2019-04-25 12:14 UTC, the-c0d3r commented on lib/connection.py
> +    def scan(self, url: str, creds) -> int:
```suggestion
    def scan(self, url: str, creds: [str, str]) -> int:
```

2019-04-25 12:14 UTC, the-c0d3r commented on lib/connection.py
> +    def __init__(self, url: str, creds) -> None:
```suggestion
    def __init__(self, url: str, creds: [str, str]) -> None:
```

2019-04-25 12:14 UTC, the-c0d3r commented on admin-finder.py
>      args.url = URLFormatter(args.url).geturl()
```suggestion
    args.url = URLFormatter(args.url).geturl()
    
    if args.credentials:
        if ":" not in args.credentials:
            print("[!] Error: credential need to be in this format user:pass")
            exit()
        args.credentials = args.credentials.split(":")
```

2019-04-25 12:14 UTC, the-c0d3r commented on admin-finder.py
> +    robot_handler = RobotHandler(args.url, args.baseauth)
```suggestion
    robot_handler = RobotHandler(args.url, args.credentials)
```

2019-04-25 12:14 UTC, the-c0d3r commented on admin-finder.py
> +            thread = WorkerThread(workQueue, args.baseauth)
```suggestion
            thread = WorkerThread(workQueue, args.credentials)
```

2019-04-25 12:14 UTC, the-c0d3r commented on lib/worker.py
> +    def __init__(self, queue: queue.Queue, creds) -> None:
```suggestion
    def __init__(self, queue: queue.Queue, creds: [str, str]) -> None:
```

2019-04-25 13:02 UTC, rusmonkey commented
@the-c0d3r, all  requested changes are made

2019-04-25 14:31 UTC, the-c0d3r commented on lib/connection.py
> +                connect to the url and return the response
Could you deindent the entire documentation block one or two levels to match the doc string starting indent?

```
    """
    connect to ...
    ...
    """
```

2019-04-25 14:32 UTC, the-c0d3r requested changes
Hey, thanks for the effort. One last final change for docstring deindentation.

2019-04-25 15:19 UTC, B4DF4C3 commented on lib/connection.py
> +                connect to the url and return the response
Sorry, it's my first contribution, seems i've fixed everything

2019-04-26 00:52 UTC, the-c0d3r approved these changes

2019-04-26 00:54 UTC, the-c0d3r commented
Thanks for the PR @B4DF4C3 and for all those adjustments. I'll merge it now. Feel free to open up more PRs 😄

2019-04-26 00:55 UTC, merged